name: Update

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  sync-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure sparse checkout for upstream
      run: |
        git remote set-url upstream https://github.com/BlankTMing/ManifestAutoUpdate/ManifestAutoUpdate.git || git remote add upstream https://github.com/BlankTMing/ManifestAutoUpdate/ManifestAutoUpdate.git
        git config core.sparseCheckout true
        echo "*.manifest" > .git/info/sparse-checkout

    - name: Sync and update .manifest files for each branch
      run: |
        for branch in $(git branch -r | grep "origin/" | sed 's/origin\///'); do
          echo "Processing branch: $branch"
          git checkout "$branch"
          git fetch --depth=1 upstream "$branch"
          git checkout upstream/"$branch" -- "*.manifest"
          if git status --short | grep -q ".manifest"; then
            echo "Changes detected in .manifest files. Committing updates."
            git add "*.manifest"
            git commit -m "Update .manifest files from upstream/$branch"
            git push origin "$branch"
          else
            echo "No changes detected for branch: $branch"
          fi
        done
